<html><head>
<meta http-equiv="content-type" content="text/html; charset=utf-8">
<link rev="made" href="mailto:webmasters@gnu.org">
<link rel="icon" type="image/png" href="/graphics/gnu-head-mini.png">
<meta name="ICBM" content="42.256233,-71.006581">
<meta name="DC.title" content="gnu.org">

<title>Catch and Throw</title>
<!--
This is the `GNU Emacs Lisp Reference Manual'
corresponding to Emacs version 24.4.

Copyright (C) 1990--1996, 1998--2014 Free Software Foundation, Inc.

     Permission is granted to copy, distribute and/or modify this
     document under the terms of the GNU Free Documentation License,
     Version 1.3 or any later version published by the Free Software
     Foundation; with the Invariant Sections being ``GNU General Public
     License,'' with the Front-Cover Texts being ``A GNU Manual,'' and
     with the Back-Cover Texts as in (a) below.  A copy of the license
     is included in the section entitled ``GNU Free Documentation
     License.''

     (a) The FSF's Back-Cover Text is: ``You have the freedom to copy
     and modify this GNU manual.  Buying copies from the FSF supports
     it in developing GNU and promoting software freedom.''
   -->
<style type="text/css">
@import url('/software/emacs/manual.css');
</style>
</head>
<body>
<div class="node" style="background-color:#DDDDFF">
<a name="Catch-and-Throw"></a>
<p>
Next:&nbsp;<a rel="next" accesskey="n" href="Examples-of-Catch.html#Examples-of-Catch">Examples of Catch</a>,
Up:&nbsp;<a rel="up" accesskey="u" href="Nonlocal-Exits.html#Nonlocal-Exits">Nonlocal Exits</a>

</p></div>

<h4 class="subsection">10.5.1 Explicit Nonlocal Exits: <code>catch</code> and <code>throw</code></h4>

<p>Most control constructs affect only the flow of control within the
construct itself.  The function <code>throw</code> is the exception to this
rule of normal program execution: it performs a nonlocal exit on
request.  (There are other exceptions, but they are for error handling
only.)  <code>throw</code> is used inside a <code>catch</code>, and jumps back to
that <code>catch</code>.  For example:

</p><pre class="example">     (defun foo-outer ()
       (catch 'foo
         (foo-inner)))
     
     (defun foo-inner ()
       ...
       (if x
           (throw 'foo t))
       ...)
</pre>
   <p class="noindent">The <code>throw</code> form, if executed, transfers control straight back to
the corresponding <code>catch</code>, which returns immediately.  The code
following the <code>throw</code> is not executed.  The second argument of
<code>throw</code> is used as the return value of the <code>catch</code>.

   </p><p>The function <code>throw</code> finds the matching <code>catch</code> based on the
first argument: it searches for a <code>catch</code> whose first argument is
<code>eq</code> to the one specified in the <code>throw</code>.  If there is more
than one applicable <code>catch</code>, the innermost one takes precedence. 
Thus, in the above example, the <code>throw</code> specifies <code>foo</code>, and
the <code>catch</code> in <code>foo-outer</code> specifies the same symbol, so that
<code>catch</code> is the applicable one (assuming there is no other matching
<code>catch</code> in between).

   </p><p>Executing <code>throw</code> exits all Lisp constructs up to the matching
<code>catch</code>, including function calls.  When binding constructs such
as <code>let</code> or function calls are exited in this way, the bindings
are unbound, just as they are when these constructs exit normally
(see <a href="Local-Variables.html#Local-Variables">Local Variables</a>).  Likewise, <code>throw</code> restores the buffer
and position saved by <code>save-excursion</code> (see <a href="Excursions.html#Excursions">Excursions</a>), and
the narrowing status saved by <code>save-restriction</code>.  It also runs
any cleanups established with the <code>unwind-protect</code> special form
when it exits that form (see <a href="Cleanups.html#Cleanups">Cleanups</a>).

   </p><p>The <code>throw</code> need not appear lexically within the <code>catch</code>
that it jumps to.  It can equally well be called from another function
called within the <code>catch</code>.  As long as the <code>throw</code> takes place
chronologically after entry to the <code>catch</code>, and chronologically
before exit from it, it has access to that <code>catch</code>.  This is why
<code>throw</code> can be used in commands such as <code>exit-recursive-edit</code>
that throw back to the editor command loop (see <a href="Recursive-Editing.html#Recursive-Editing">Recursive Editing</a>).

   </p><p><a name="index-CL-note_002d_002d_002donly-_0040code_007bthrow_007d-in-Emacs-579"></a></p><blockquote>
<b>Common Lisp note:</b> Most other versions of Lisp, including Common Lisp,
have several ways of transferring control nonsequentially: <code>return</code>,
<code>return-from</code>, and <code>go</code>, for example.  Emacs Lisp has only
<code>throw</code>.  The <samp><span class="file">cl-lib</span></samp> library provides versions of some of
these.  See <a href="../cl/Blocks-and-Exits.html#Blocks-and-Exits">Blocks and Exits</a>. 
</blockquote>

<div class="defun">
<a class="dashAnchor" name="//apple_ref/func/catch"></a><a name="DASH-336"></a>— Special Form: <b>catch</b><var> tag body<small class="dots">...</small><a name="index-catch-580"></a></var><br>
<blockquote><p><a name="index-tag-on-run-time-stack-581"></a><code>catch</code> establishes a return point for the <code>throw</code> function. 
The return point is distinguished from other such return points by
<var>tag</var>, which may be any Lisp object except <code>nil</code>.  The argument
<var>tag</var> is evaluated normally before the return point is established.

        </p><p>With the return point in effect, <code>catch</code> evaluates the forms of the
<var>body</var> in textual order.  If the forms execute normally (without
error or nonlocal exit) the value of the last body form is returned from
the <code>catch</code>.

        </p><p>If a <code>throw</code> is executed during the execution of <var>body</var>,
specifying the same value <var>tag</var>, the <code>catch</code> form exits
immediately; the value it returns is whatever was specified as the
second argument of <code>throw</code>. 
</p></blockquote></div>

<div class="defun">
<a class="dashAnchor" name="//apple_ref/func/throw"></a><a name="DASH-337"></a>— Function: <b>throw</b><var> tag value<a name="index-throw-582"></a></var><br>
<blockquote><p>The purpose of <code>throw</code> is to return from a return point previously
established with <code>catch</code>.  The argument <var>tag</var> is used to choose
among the various existing return points; it must be <code>eq</code> to the value
specified in the <code>catch</code>.  If multiple return points match <var>tag</var>,
the innermost one is used.

        </p><p>The argument <var>value</var> is used as the value to return from that
<code>catch</code>.

        </p><p><a name="index-no_002dcatch-583"></a>If no return point is in effect with tag <var>tag</var>, then a <code>no-catch</code>
error is signaled with data <code>(</code><var>tag</var> <var>value</var><code>)</code>. 
</p></blockquote></div>

   

</body></html>